language: python
python:
  - 3.5
sudo: false
install:
- pip install tox coveralls
env:
  - TOXENV=py27-django16
  - TOXENV=py34-django16
  - TOXENV=pypy-django16
  - TOXENV=py27-django17
  - TOXENV=py34-django17
  - TOXENV=pypy-django17
  - TOXENV=py27-django18
  - TOXENV=pypy-django18
  - TOXENV=py34-django18
  - TOXENV=py27-django19
  - TOXENV=pypy-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=py27-django110
  - TOXENV=pypy-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110
docsinstall: pip install -q tox
before_install:
  - nvm install node
  - nvm use node
install:
  - pip install -r requirements.txt
  - npm install
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: rECBwGxp/D0BcaNe6lW0XSjLOMkQLXm/Etft+l+wxhZZxkoaS5t38pWb1/wvWBuPa9I0GagRPbqap72PYJeEgS4BIgsIP8YRTxkggDJ6+CtecyMBxWWSKc94QW/x2HETQ1cYGsLwXgMEGV4WkjzKUUM3SYTjfz0jkMfMv0szufQ=
  on:
    tags: true
    repo: jazzband/django-pipeline
    condition: "$TOXENV = py27-django19"
notifications:
  email: false
