language: python
sudo: false
matrix:
  include:
    - env: TOXENV=py27-django16
      python: "2.7"
    - env: TOXENV=pypy-django16
      python: "pypy"
    - env: TOXENV=py34-django16
      python: "3.4"
    - env: TOXENV=py27-django17
      python: "2.7"
    - env: TOXENV=pypy-django17
      python: "pypy"
    - env: TOXENV=py34-django17
      python: "3.4"
    - env: TOXENV=py27-django18
      python: "2.7"
    - env: TOXENV=pypy-django18
      python: "pypy"
    - env: TOXENV=py34-django18
      python: "3.4"
    - env: TOXENV=py27-django19
      python: "2.7"
    - env: TOXENV=pypy-django19
      python: "pypy"
    - env: TOXENV=py34-django19
      python: "3.4"
    - env: TOXENV=py35-django19
      python: "3.5"
    - env: TOXENV=py27-django110
      python: "2.7"
    - env: TOXENV=pypy-django110
      python: "pypy"
    - env: TOXENV=py34-django110
      python: "3.4"
    - env: TOXENV=py35-django110
      python: "3.5"
    - env: TOXENV=py27-django111
      python: "2.7"
    - env: TOXENV=pypy-django111
      python: "pypy"
    - env: TOXENV=py34-django111
      python: "3.4"
    - env: TOXENV=py35-django111
      python: "3.5"
    - env: TOXENV=py36-django111
      python: "3.6"
    - env: TOXENV=py34-django-master
      python: "3.4"
    - env: TOXENV=py35-django-master
      python: "3.5"
    - env: TOXENV=py36-django-master
      python: "3.6"
    - env: TOXENV=docs
      python: "2.7"
  allow_failures:
    - env: TOXENV=py34-django-master
    - env: TOXENV=py35-django-master
    - env: TOXENV=py36-django-master
before_install:
  - nvm install node
  - nvm use node
install:
  - pip install -r requirements.txt
  - npm install
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  password:
    secure: rECBwGxp/D0BcaNe6lW0XSjLOMkQLXm/Etft+l+wxhZZxkoaS5t38pWb1/wvWBuPa9I0GagRPbqap72PYJeEgS4BIgsIP8YRTxkggDJ6+CtecyMBxWWSKc94QW/x2HETQ1cYGsLwXgMEGV4WkjzKUUM3SYTjfz0jkMfMv0szufQ=
  on:
    tags: true
    repo: jazzband/django-pipeline
    condition: "$TOXENV = py27-django111"
notifications:
  email: false
